version: '3.8'

services:
  db:
    image: postgres:16
    container_name: tenpo_db
    restart: always
    environment:
      POSTGRES_DB: tenpo_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d tenpo_db"]
      interval: 10s
      retries: 5
      start_period: 20s

  app:
    build: .
    container_name: backend_app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/tenpo_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

volumes:
  postgres_data:
