server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tenpo_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  cache:
    type: caffeine  # Usaremos Caffeine como caché en memoria

logging:
  level:
    org.hibernate.SQL: debug
